# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170805_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
